# NB: We generally recommend using Issuers rather than ClusterIssuers with istio-csr.
# Issuers are easier to scope, and therefore easier to reason about in terms of security.

# SelfSigned issuers are useful for creating root certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# Request a self-signed certificate from our ClusterIssuer; this will function as our
# issuing root certificate when we pass it into a CA ClusterIssuer.

# It's generally fine to issue root certificates like this one with long lifespans;
# the certificates which istio-csr issues will be much shorter lived.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
    - cluster.local
    - cert-manager
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
# Create a CA issuer using our root. This will be the ClusterIssuer which istio-csr will use.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-ca
spec:
  ca:
    secretName: istio-ca
