stages:
- build
- docker
- deploy-staging
- deploy-prod

variables:
  DOCKER_HOST: tcp://localhost:2375

before_script:
- echo "${GCLOUD_SVC_ACCT}" > gcloud-svc-acct.json && chmod 600 gcloud-svc-acct.json
- export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/gcloud-svc-acct.json"
- gcloud auth activate-service-account --key-file gcloud-svc-acct.json

test:helm:
  before_script: []
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: build
  tags:
  - docker
  script:
  - make test_helm

build:hugo:
  before_script: []
  image: docker:1.13.1
  stage: build
  script:
  - apk add --no-cache make
  - make hugo_build
  services:
  - docker:1.13.1-dind
  artifacts:
    paths:
    - ./_output
  tags:
  - docker

build:golang:
  before_script: []
  image: docker:1.13.1
  stage: build
  script:
  - apk add --no-cache make
  - make golang_build
  services:
  - docker:1.13.1-dind
  artifacts:
    paths:
    - ./_build
  tags:
  - docker

docker:image:
  before_script: []
  image: docker:1.13.1
  stage: docker
  tags:
  - docker
  script:
  - apk add --no-cache make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_build docker_push IMAGE_TAGS="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
  services:
  - docker:1.13.1-dind
  dependencies:
  - build:hugo
  - build:golang

deploy:staging:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: deploy-staging
  tags:
  - docker
  script:
  - make deploy
      ENVIRONMENT="${CI_ENVIRONMENT_NAME}"
      IMAGE_TAG="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
      INGRESS_HOSTNAMES="website-staging.kube.jetstack.net"
      HUGO_BASE_URL="https://website-staging.kube.jetstack.net"
      TLS_ENABLED=true
      HELM_VALUES='.values.staging.yaml'
      REPLICA_COUNT=1
  environment:
    name: staging
    url: https://website-staging.kube.jetstack.net
  only:
  - master

deploy:review:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: deploy-staging
  tags:
  - docker
  script:
  - make deploy
      ENVIRONMENT="${CI_BUILD_REF_SLUG}"
      IMAGE_TAG="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
      INGRESS_HOSTNAMES="${CI_BUILD_REF_SLUG}.website.kube.jetstack.net"
      TLS_ENABLED=false
      HUGO_BASE_URL="http://${CI_BUILD_REF_SLUG}.website.kube.jetstack.net"
      NAMESPACE="website-review"
      HELM_VALUES='.values.staging.yaml'
      REPLICA_COUNT=1
  environment:
    name: ${CI_BUILD_REF_SLUG}
    url: http://${CI_BUILD_REF_SLUG}.website.kube.jetstack.net
    on_stop: deploy:review:stop
  only:
  - branches
  except:
  - master

deploy:review:stop:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: deploy-staging
  tags:
  - docker
  script:
  - make destroy
      ENVIRONMENT="${CI_BUILD_REF_SLUG}"
      NAMESPACE="website-review"
      SURE=1
  when: manual
  environment:
    name: ${CI_BUILD_REF_SLUG}
    action: stop
  only:
  - branches
  except:
  - master

deploy:prod:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: deploy-prod
  tags:
  - docker
  script:
  - make deploy
      ENVIRONMENT="${CI_ENVIRONMENT_NAME}"
      IMAGE_TAG="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
      INGRESS_HOSTNAMES="www.jetstack.io,jetstack.io"
      HUGO_BASE_URL="https://www.jetstack.io"
      HTPASSWD=
      TLS_ENABLED=true
      TLS_DNS_PROVIDER=jetstack-gke-clouddns
      HELM_VALUES='.values.prod.yaml'
  environment:
    name: prod
    url: https://www.jetstack.io
  when: manual
  only:
  - master
