stages:
- build
- docker
- deploy

test:helm:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: build
  tags:
  - docker
  script:
  - make test_helm

build:hugo:
  image: docker:1.13.1
  stage: build
  script:
  - apk add --no-cache make
  - make hugo_build
  services:
  - docker:1.13.1-dind
  artifacts:
    paths:
    - ./_output
  tags:
  - docker

build:golang:
  image: docker:1.13.1
  stage: build
  script:
  - apk add --no-cache make
  - make golang_build
  services:
  - docker:1.13.1-dind
  artifacts:
    paths:
    - ./_build
  tags:
  - docker

docker:image:
  image: docker:1.13.1
  stage: docker
  tags:
  - docker
  script:
  - apk add --no-cache make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_build docker_push IMAGE_TAGS="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
  services:
  - docker:1.13.1-dind
  dependencies:
  - build:hugo
  - build:golang

deploy:staging:
  image: eu.gcr.io/jetstack-gke/infrastructure:latest
  stage: deploy
  tags:
  - docker
  script:
  - mkdir -p ~/.kube && echo "${KUBECONFIG_DATA}" > ~/.kube/config && chmod 600 ~/.kube/config
  - make deploy ENVIRONMENT="${CI_ENVIRONMENT_NAME}" IMAGE_TAG="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID}"
  environment:
    name: staging
    url: https://website-staging.kube.jetstack.net
  only:
  - master
