config:
  smtpUsername: AKIAJYHII4ZIATIRLUJQ
  smtpPassword: Asz8vI0W5X1hF07QcoIMKsc6klLEYPQyBidAxewrE/E6
ingressTLS: false
ingressHostnames:
- website-prodd.kube.jetstack.net
- website-prod2.kube.jetstack.net
