ingressTLS: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.jetstack.net/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.jetstack.net"
  hosts:
    - host: testenv.website.kube.jetstack.net
      paths: [/]
  tls:
    - secretName: wildcard-website-kube-jetstack-net
      hosts:
        - testenv.website.kube.jetstack.net
