apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SMTP_PORT
          value: {{ .Values.config.smtpPort | quote }}
        - name: SMTP_HOST
          value: {{ .Values.config.smtpHost | quote }}
        - name: SMTP_USERNAME
          value: {{ .Values.config.smtpUsername | quote }}
        - name: SMTP_PASSWORD
          value: {{ .Values.config.smtpPassword | quote }}
        - name: CONTACT_SENDER_ADDRESS
          value: {{ .Values.config.contactSenderAddress| quote }}
        - name: CONTACT_DEST_ADDRESS
          value: {{ .Values.config.contactDestAddress| quote }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
