{{- $global := . }}
{{- if gt (len .Values.ingressHostnames) 0 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: '{{ .Values.ingressClass }}'
{{- if gt (len .Values.ingressHtpasswd) 0 }}
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: {{ template "fullname" $global }}-htpasswd
    ingress.kubernetes.io/auth-realm: "Authentication Required - Jetstack"
{{- end }}
{{- if .Values.ingressTLS }}
    kubernetes.io/tls-acme: "true"
{{- if .Values.ingressTLSDNSProvider }}
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: {{ .Values.ingressTLSDNSProvider }}
{{- end }}
{{- end }}
spec:
{{- if .Values.ingressTLS }}
  tls:
  - secretName: {{ template "fullname" $global }}
    hosts:
{{- range $hostname := .Values.ingressHostnames }}
    - {{ $hostname }}
{{- end }}
{{- end }}
  rules:
{{- range $hostname := .Values.ingressHostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" $global }}
          servicePort: {{ $global.Values.service.externalPort }}
{{- end }}
{{- end }}
