{{- $global := . }}
{{- range $target, $hostnames := .Values.ingressRedirectHostnames }}
{{- $redirectName := . }}
---
{{- if semverCompare ">=1.14-0" $global.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "jetstack-website.fullname" $global }}-{{ template "redirectname" $target }}
  labels:
    {{- include "jetstack-website.labels" $global | nindent 4 }}

{{- $annotations := $global.Values.ingress.annotations  }}
{{- $_ := set $annotations "nginx.ingress.kubernetes.io/configuration-snippet" (include "redirectconfig" $target) }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}

spec:
  tls:
  - secretName: {{ template "jetstack-website.fullname" $global }}-{{ template "redirectname" $target }}
    hosts:
{{- range $hostname := $hostnames }}
    - {{ $hostname }}
{{- end }}
  rules:
{{- range $hostname := $hostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "jetstack-website.fullname" $global }}
          servicePort: {{ $global.Values.service.externalPort }}
{{- end }}
{{- end }}
