apiVersion: v1
kind: Service
metadata:
  name: {{ include "jetstack-website.fullname" . }}
  labels:
    {{- include "jetstack-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    {{- include "jetstack-website.selectorLabels" . | nindent 4 }}
