# Default values for jetstack-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
minReadySeconds: 60
image:
  repository: eu.gcr.io/jetstack-gke/website
  tag: stable
  pullPolicy: Always
service:
  name: site
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  requests:
    cpu: 50m
    memory: 10Mi
  limits:
    cpu: 500m
    memory: 100Mi
ingressClass: nginx
ingressHostnames: []
ingressTLS: true
