# Default values for jetstack-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
minReadySeconds: 60
image:
  repository: eu.gcr.io/jetstack-gke/website
  tag: stable
  pullPolicy: Always
service:
  name: site
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 10Mi
  limits:
    cpu: 500m
    memory: 100Mi
config:
  smtpPort: "2587"
  smtpHost: email-smtp.eu-west-1.amazonaws.com
  smtpUsername: xx
  smtpPassword: yy
  contactSenderAddress: website@jetstack.net
  contactDestAddress: hello@jetstack.io
ingressClass: nginx
ingressHostnames: []
ingressRedirectHostnames: {}
ingressTLS: true
ingressTLSDNSProvider: ""
ingressHtpasswd: ""
