apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sleep-auto
  name: sleep-auto
  namespace: team-a
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sleep-auto
  strategy: {}
  template:
    metadata:
      labels:
        app: sleep-auto
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 1d
        image: quay.io/zenlab/curl:latest
        name: curl
        resources: {}
        volumeMounts:
          - mountPath: /etc/ssl/certs/
            name: ca-certificate-only
            readOnly: true
      volumes:
        - name: ca-certificate-only
          configMap:
            name: public-bundle
            defaultMode: 0644
            optional: false
            items:
            - key: ca-certificates.crt
              path: ca-certificates.crt
