apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 3
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: site
          image: '{{IMAGE}}'
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 3
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 3
            timeoutSeconds: 2
            httpGet:
              path: /
              port: 80
