#!/usr/bin/env bash

# This script constructs a 'content/' directory that contains content for all
# configured versions of the documentation.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

"${REPO_ROOT}/scripts/update-node_modules"
"${REPO_ROOT}/scripts/update-theme"
"${REPO_ROOT}/scripts/bin/hugo" "$@"

# Move _redirects file into public/ directory as per https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file
\cp "${REPO_ROOT}/_redirects" "${REPO_ROOT}/public/"
