#!/usr/bin/env bash

# Copyright 2022 The cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# code relating to "entr" taken from an MIT-licensed closed source project (maintained by https://github.com/SgtCoDFish)

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

# This script runs a local development server fronted by the netlify CLI.
# This allows redirect rules and netlify environment variables to be tested locally.

# Note that this runs _both_ the next.js development server (via scripts/server) on port 3000
# *and* the netlify frontend server, which is on port 8888.

# You'll want to use port 8888 for most use cases since that'll have working redirects!

NETLIFY_CLI="netlify"

ENTR="entr"

if ! command -v "${NETLIFY_CLI}" >/dev/null ; then
	echo "+++ missing required command: ${NETLIFY_CLI}. Install through npm or homebrew first"
	exit 1
fi

if ! command -v ${ENTR} >/dev/null ; then
	# entr allows us to hot-reload public/_redirects
	# but if it's not installed we should still work!
	echo "⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️"
	echo "Changes to public/_redirects will not be hot reloaded!"
	echo "If you're changing redirects, close and re-run server-netlify to pick up the changes"
	echo "Alternatively, install '${ENTR}' and re-run this script to enable hot reloading!"
	echo "⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️"

	sleep 1
else
	# entr will watch the files listed in STDIN and then run the associated command when those files change
	(echo "${REPO_ROOT}/public/_redirects" | ${ENTR} cp "${REPO_ROOT}/public/_redirects" "${REPO_ROOT}/out/") &
fi

mkdir -p "${REPO_ROOT}/out/"
cp "${REPO_ROOT}/public/_redirects" "${REPO_ROOT}/out/"

# Setting BROWSER="none" stops the CLI from opening a new tab in your browser when you run the script

BROWSER="none" ${NETLIFY_CLI} dev --command "${REPO_ROOT}/scripts/server" --offline --port 8888
