#!/usr/bin/env bash

# Copyright 2022 The cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# NOTE: You probably want ./scripts/server for most development work. Rebuilding
# API docs is not likely to be a hugely beneficial thing for most changes a user
# might want to make for the website and is likely to do nothing but slow you down.

# This script rebuilds the API + CLI docs for the latest version of cert-manager
# and then runs the development server. This will be a good approximation of the
# end result when running the deployed site.

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

"${REPO_ROOT}/scripts/build-release"
"${REPO_ROOT}/scripts/server"
