#!/usr/bin/env bash

# Copyright 2019 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script uses the 'multiversion' tool to fetch additional documentation
# content/ directories from each release branch for the documentation.
# This script only needs to be run when building a full multi-version copy
# of the docs site.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT=$(dirname "${BASH_SOURCE[0]}")/..

"${REPO_ROOT}/scripts/bin/multiversion" \
	--repo-url https://github.com/cert-manager/docs.git \
	--repo-content-dir docs/ \
	--output-dir "${REPO_ROOT}/content/docs" \
	# Uncomment the below lines when we cut the release-0.12 branch
	# --latest-branch master \
	# --branches v0.11-docs=master
