#!/usr/bin/env bash

# Copyright 2019 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script uses the 'multiversion' tool to fetch additional documentation
# content/ directories from each release branch for the documentation.
# This script only needs to be run when building a full multi-version copy
# of the docs site.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

# The branches named here exist in the 'cert-manager/website' repo.
"${REPO_ROOT}/scripts/bin/multiversion" \
	--repo-url https://github.com/cert-manager/website.git \
	--repo-content-dir content/en/docs \
	--output-dir "${REPO_ROOT}/content/en" \
	--branches v1.7-docs=release-1.7 \
	--branches v1.6-docs=release-1.6 \
	--branches v1.5-docs=release-1.5 \
	--branches v1.4-docs=release-1.4 \
	--branches v1.3-docs=release-1.3 \
	--branches v1.2-docs=release-1.2 \
	--branches v1.1-docs=release-1.1 \
	--branches v1.0-docs=release-1.0 \
	--branches v0.16-docs=release-0.16 \
	--branches v0.15-docs=release-0.15 \
	--branches v0.14-docs=release-0.14 \
	--branches v0.13-docs=release-0.13 \
	--branches v0.12-docs=release-0.12 \
	--branches next-docs=release-next
