#!/usr/bin/env bash

# Ensures the themes/docsy directory exists and is up to date

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}/themes/docsy"
git submodule update -f --init
cd ../..
