#!/usr/bin/env bash

# Copyright 2019 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

"${REPO_ROOT}/scripts/update-node_modules"

echo "+++ Running remark"
"${REPO_ROOT}/node_modules/.bin/remark" \
  --rc-path ".remarkrc" \
  --frail \
  content/

echo "+++ Running spell check"
"${REPO_ROOT}/node_modules/.bin/mdspell" \
  --report \
  --en-us \
  --ignore-numbers \
  --ignore-acronyms \
  "content/**/*.md" \
  "content/**/*.html" \
  "_layouts/*.html" \
  "_includes/*.html" \
  "*.html" \
  "!content/en/docs/reference/api-docs.md" \
  "!content/en/v0.12-docs/reference/api-docs.md" \
  "!content/en/v0.13-docs/reference/api-docs.md" \
  "!content/en/v0.14-docs/reference/api-docs.md" \
  "!content/en/v0.15-docs/reference/api-docs.md" \
  "!content/en/v0.16-docs/reference/api-docs.md" \
  "!content/en/v1.0-docs/reference/api-docs.md" \
  "!content/en/v1.1-docs/reference/api-docs.md" \
  "!content/en/v1.2-docs/reference/api-docs.md" \
  "!content/en/v1.3-docs/reference/api-docs.md" \
  "!content/en/v1.4-docs/reference/api-docs.md" \
  "!content/en/v1.5-docs/reference/api-docs.md" \
  "!content/en/v1.6-docs/reference/api-docs.md" \
  "!content/en/v1.7-docs/reference/api-docs.md" \
  "!content/en/next-docs/**/*.md"

# About "!content/en/next-docs/**/*.md":
#
# mdspell can fail on master due to words that have been added to the
# release-next branch and aren't on master yet. Since we pull the release-next
# branch into content/en/next-docs, the yet-to-be-ignored words are unknown to
# mdspell.
#
# As an example, the PR https://github.com/cert-manager/website/pull/570 added
# the new spellings "andreas-p" and "renewBefore" to the release-next branch.
# After the merge, all builds on master started failing since "andreas-p" and
# "renewBefore" were not present on the master branch's .spelling file.
