#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

"${REPO_ROOT}/scripts/update-node_modules"

echo "+++ Running 'alex' - ignoring any failures"
"${REPO_ROOT}/node_modules/.bin/alex" \
  content/ || true

echo "+++ Running remark"
"${REPO_ROOT}/node_modules/.bin/remark" \
  --rc-path ".remarkrc" \
  --frail \
  content/

echo "+++ Running spell check"
"${REPO_ROOT}/node_modules/.bin/mdspell" \
  --report \
  --en-us \
  --ignore-numbers \
  --ignore-acronyms \
  "content/**/*.md" \
  "content/**/*.html" \
  "_layouts/*.html" \
  "_includes/*.html" \
  "*.html" \
  "!content/en/docs/reference/api-docs.md" \
  "!content/en/v0.12-docs/reference/api-docs.md" \
  "!content/en/v0.13-docs/reference/api-docs.md" \
  "!content/en/v0.14-docs/reference/api-docs.md" \
  "!content/en/v0.15-docs/reference/api-docs.md" \
  "!content/en/v0.16-docs/reference/api-docs.md" \
  "!content/en/v1.0-docs/reference/api-docs.md" \
  "!content/en/next-docs/reference/api-docs.md"
