#!/usr/bin/env bash

# Copyright 2019 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# This script constructs a 'content/' directory that contains content for all
# configured versions of the documentation.
#
# It then runs all the verify-*.sh scripts against this copy of the website in
# order to ensure the final version of the site to be published passes all
# verification steps.

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

# Run all commands relative to the repository root
cd "${REPO_ROOT}"

export HUGO_ENV="production"

# Fetch all required content versions & assemble the content/ directory
"${REPO_ROOT}/scripts/build-release"

# 3. Run ./scripts/verify-all.sh
"${REPO_ROOT}/scripts/verify"
