#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

"${REPO_ROOT}/scripts/verify-links"
"${REPO_ROOT}/scripts/verify-lint"
