#!/usr/bin/env bash

# Copyright 2019 The Jetstack cert-manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"

cd "${REPO_ROOT}"

"${REPO_ROOT}/scripts/update-node_modules"

echo "+++ Running 'alex' - ignoring any failures"
"${REPO_ROOT}/node_modules/.bin/alex" \
	content/ || true

echo "+++ Running remark"
"${REPO_ROOT}/node_modules/.bin/remark" \
	--rc-path ".remarkrc" \
	--frail \
	content/

echo "+++ Running spell check"
"${REPO_ROOT}/node_modules/.bin/mdspell" \
  --report \
  --en-us \
  --ignore-numbers \
  --ignore-acronyms \
  "content/**/*.md" \
  "content/**/*.html" \
  "_layouts/*.html" \
  "_includes/*.html" \
  "*.html" \
  "!content/en/docs/reference/api-docs.md" \
  "!content/en/v0.12-docs/reference/api-docs.md" \
  "!content/en/v0.13-docs/reference/api-docs.md" \
  "!content/en/v0.14-docs/reference/api-docs.md" \
  "!content/en/v0.15-docs/reference/api-docs.md" \
  "!content/en/next-docs/reference/api-docs.md"
