apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-revision
  namespace: default
spec:
  dnsNames:
  - example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: not-my-corp-issuer
  secretName: test-revision-cert
